stages:
  - test
  - build

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

before_script:
  - export MAVEN_HOME=$(mvn -B --version | grep 'Maven home' | awk '{print $3}')
  - export PATH=$MAVEN_HOME/bin:$PATH

test_job:
  image: maven:3.8.1-openjdk-17  # Use an image that includes Maven
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

build_job:
  image: maven:3.8.1-openjdk-17  # Use an image that includes Maven
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean install
  artifacts:
    paths:
      - target/*.jar
