name: Java CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Test
        run: mvn --batch-mode --errors --fail-at-end --show-version test --settings .m2/settings.xml

  build:
    runs-on: ubuntu-latest

    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build
        run: mvn --batch-mode clean install --settings .m2/settings.xml

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-jar
          path: target/*.jar
